name: 'Test Windows'
description: 'Runs Windows tests'
inputs:
  electron:
    description: 'Electron version'
    required: true

runs:
  using: "composite"
  steps:
    - uses: agracio/github-substring-action@v1.0.0
      id: electron_version
      with:
        value: "${{ inputs.electron }}"
        length_from_start: 2

    - name: Check electron-edge-js Windows pre-built files
      uses: andstor/file-existence-action@v3
      with:
        files: "lib/native/win32/${{ runner.arch }}/${{ steps.electron_version.outputs.substring }}.0.0/edge_coreclr.node, lib/native/win32/${{ runner.arch }}/${{ steps.electron_version.outputs.substring }}.0.0/edge_nativeclr.node"
        fail: true
        ignore_case: true

    - name: Run .NET 4.5 tests Windows
      shell: bash
      run: node tools/test.js CI

    - name: "Run .net core tests Windows"
      shell: bash
      run: node tools/test.js CI
      env:
        EDGE_USE_CORECLR: 1
