name: 'Test report'
description: 'Create test report'
inputs:
  name:
    description: 'name'
    required: false
    default: 'test-results'
  electron:
    description: 'Electron version'
    required: true
  os:
    description: 'runs-on'
    required: true

runs:
  using: "composite"
  steps:
    - name: "Merge test files"
      shell: bash
      run: node tools/mergeTests.js ${{ inputs.electron }}

    - name: Read mochawesome.json
      uses: actions/github-script@v7
      with:
        result-encoding: string
        script: |
          try {
            const fs = require('fs')
            const jsonString = fs.readFileSync('test/mochawesome-report/mochawesome.json')
            var report = JSON.parse(jsonString);
            let stats = {
                passing: report.stats.passes,
                skipped: report.stats.pending,
                failures: report.stats.failures
            };
            core.notice(JSON.stringify(stats));
          } catch(err) {
            core.error("Error while reading or parsing test/mochawesome-report/mochawesome.json")
            core.setFailed(err)
          }

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: ${{ inputs.name }}-${{ inputs.os }}-${{ inputs.electron }}
        path: |
          test/mochawesome-report/mochawesome.json
          # test/mochawesome-report/mochawesome.html
          # test/mochawesome-report/assets/

    - name: Create test report
      uses: phoenix-actions/test-reporting@v15
      if: success()
      with:
        name: ${{ inputs.name }}-${{ inputs.os }}-v${{ inputs.electron }}
        fail-on-error: true
        path: test/mochawesome-report/mochawesome.json   # Path to test results
        reporter: mochawesome-json 
