name: 'Test report'
description: 'Create test report'
inputs:
  name:
    description: 'name'
    required: false
    default: 'test-results'
  electron:
    description: 'Electron version'
    required: true
  os:
    description: 'runs-on'
    required: true
  upload:
    description: 'Upload artifacts?'
    required: false
    default: 'true'

runs:
  using: "composite"
  steps:
    - name: "Merge test files"
      shell: bash
      run: node tools/mergeTests.js ${{ inputs.electron }}

    - name: Test report
      uses: actions/github-script@v7
      with:
        result-encoding: string
        script: |
          try {
            const fs = require('fs')
            const jsonString = fs.readFileSync('mochawesome.json')
            var report = JSON.parse(jsonString);

            let duration = Number(report.stats.duration) || (report.stats.end - report.stats.start);
            let time;
            if(duration < 1000){
              time = `${duration}ms`;
            }
            else{
              time = `${(duration / 1000).toFixed(3)}s`;
            }

            let skipped = report.stats.pending == 0 ? '' : `${report.stats.pending} ➖`;

            let resultTable = [
              [{data: 'Passed', header: true}, {data: 'Failed', header: true}, {data: 'Skipped', header: true}, {data: 'Time', header: true}],
              [`${report.stats.passes} ✔️`, `${report.stats.failures} ❌`, `${skipped} `, `${time}`]
            ];
            core.summary.addHeading(`Test results`, 4);
            core.summary.addTable(resultTable);
            if(Number(report.stats.failures) > 0) {
                let failures = {}
                if(report.results?.length !== 0 ) {
                    for (let i = 0; i < report.results.length; i++) {
                        report.results[i].suites = report.results[i].suites.filter((suite) =>suite.tests.filter((test) => test.fail).length > 0);
                        for (let j = 0; j < report.results[i].suites.length; j++) {
                            report.results[i].suites[j].tests = report.results[i].suites[j].tests.filter((test) => test.fail);
                            report.results[i].suites[j].file = report.results[i].suites[j].file?.replaceAll('\\', '/');
                            if(report.results[i].suites[j].file?.startsWith('/')) {
                                report.results[i].suites[j].file = report.results[i].suites[j].file.substring(1);
                            }
                            let suite = report.results[i].suites[j];
                            let name = suite.file && suite.file !== '' ?  suite.file : suite.title;
                            failures[name] = failures[name] || [];
                            failures[name].title = failures[name].title || suite.title;
                            failures[name].text = failures[name].text || suite.title;
                            for (const test of suite.tests) {
                              let message = test.err.message;
                              if(message) {
                                  message = message.replaceAll('\n', '  ');
                              }

                              failures[name].text += `\n  ❌ ${test.title}\n      ${message}`;
                            }
                        }
                    }
                }
                for(const key in failures) {
                    let failure = failures[key];
                    core.summary.addHeading(`❌ ${key}`, 5);
                    core.summary.addCodeBlock(failure.text, 'bash');
                }
            }
            core.summary.write();
            if(Number(report.stats.failures) > 0) {
              core.setFailed(`There are ${report.stats.failures} test failures`);
            }
          } catch(err) {
            core.error("Error while reading or parsing mochawesome.json")
            core.setFailed(err)
          }

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      if: ${{ inputs.upload == 'true' && success() }}
      with:
        name: ${{ inputs.name }}-${{ inputs.os }}-${{ inputs.electron }}
        path: |
          test/mochawesome-report/mochawesome.json
          test/mochawesome-report/mochawesome.html
          test/mochawesome-report/assets/
