name: Build

on:
  workflow_dispatch:
    inputs:
      electron:
        description: 'Electron version to build'
        required: true
        default: '30'
        type: choice
        options:
        - 30
        - 31
        - 32
        - 33
        - 34
        - 35
        - 36

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1 
  DOTNET_NOLOGO: 1

jobs:
  build:
    runs-on: ${{ matrix.os }}
    outputs:
      test-version: ${{ steps.electron-test-version.outputs.test-version }}
    strategy:
      matrix:
        # os: [macos-13, macos-15]
        os: [windows-2022, windows-2025, macos-13, macos-15]
      fail-fast: true
       
    name: build electron-${{ inputs.electron }} ${{ matrix.os }}
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: npm install
        shell: bash
        run: npm i

      - name: Get latest Electron version for ${{ inputs.electron }}
        id: electron-test-version
        shell: bash
        run: |
          node tools/getVersion.js ${{ inputs.electron }}
          echo "test-version=$(cat electron.txt)" >> $GITHUB_OUTPUT
   
      - name: Build Electron ${{ inputs.electron }}
        uses: ./.github/actions/build-electron
        with:
          electron: ${{ inputs.electron }}
          os: ${{ matrix.os }}


  upload-artifacts:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      fail-fast: false

    name: upload artifacts electron-${{ inputs.electron }}
    steps:

      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: Upload artifacts
        uses: actions/upload-artifact/merge@v4
        if: success()
        with:
          name: electron-edge-js-${{ inputs.electron }}
  
  test:
    runs-on: ${{ matrix.os }}
    needs: build
    strategy:
      matrix:
        # os: [windows-2022]
        os: [windows-2022, windows-2025, macos-13, macos-15]
      fail-fast: false

    name: test electron-${{ needs.build.outputs.test-version }} ${{ matrix.os }}
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test build
        uses: ./.github/actions/test-build
        timeout-minutes: 10
        with:
          electron: ${{ needs.build.outputs.test-version }}
          os: ${{ matrix.os }}
  
    